# Generated by Django 5.1.2 on 2024-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryhello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_id2',
        ),
    ]
