# Generated by Django 5.1.2 on 2024-10-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryhello', '0002_rename_student_id_student_student_id2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id2',
            new_name='student_id',
        ),
    ]
